site_name: 我的技术文档
site_url: https://spiritn.github.io/note-doc/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
  features:
    - search.highlight
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.copy

plugins:
  - search

# 使用 CDN 加速静态资源
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 引入自定义CSS，显著增强字体和排版
extra_css:
  - stylesheets/extra.css

# 导航
nav:
  - 首页: index.md
  - 数据库: 
    - mySQL架构: database/02-mysql架构.md
    - 基础: database/00-基础.md
    - InnoDB存储引擎: database/03-InnoDB存储引擎.md
    - 索引: database/04-索引.md
    - 日志系统: database/05-日志系统.md

  - Java:
    - JAVA8: java/java8.md
    - spring: java/spring/spring/IocContainer.md